packages:
  - "."

minimumReleaseAge: 0
onlyBuiltDependencies:
  - esbuild
  - sharp
ignoredBuiltDependencies:
  - "@scarf/scarf"
  - keytar
  - puppeteer
allowBuilds:
  '@scarf/scarf': true
  esbuild: true
  keytar: true
  puppeteer: true
  sharp: true
