packages:
  - "."

minimumReleaseAge: 0
onlyBuiltDependencies:
  - esbuild
  - sharp
ignoredBuiltDependencies:
  - "@scarf/scarf"
  - keytar
  - puppeteer
allowBuilds:
  '@scarf/scarf': set this to true or false
  esbuild: set this to true or false
  keytar: set this to true or false
  puppeteer: set this to true or false
  sharp: set this to true or false
