name: Sync and update api reference pages

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  mintlify-docs:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AMPERSAND_OPS_PAT }}
          ref: main

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Check for changes in the docs
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'v1.0-mintlify/**'

      - name: Notify if no changes have happened since last run
        if: steps.filter.outputs.docs == 'false'
        run: echo 'No changes since last run'
        shell: bash

      - name: Generate API ref pages if any docs file has changed
        if: steps.filter.outputs.docs == 'true'
        run: cd v1.0-mintlify && pnpm i && pnpm run generate
        shell: bash

      - name: Push changes
        if: steps.filter.outputs.docs == 'true'
        run: |
          git config --global user.email "devops@withampersand.com"
          git config --global user.name "Ampersand Ops"
          git add v1.0-mintlify/
          git commit -m "[ampersand-ops] auto: update documentation with latest api reference"
          git remote set-url origin https://x-access-token:${{ secrets.AMPERSAND_OPS_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.AMPERSAND_OPS_PAT }}
