name: Sync and update api reference pages

on:
  pull_request:
    types: [closed]
    branches:
      - main
  repository_dispatch:
    types: [update-docs-trigger]

jobs:
  mintlify-docs:
    permissions: write-all
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || (github.event_name == 'repository_dispatch' && github.event.action == 'update-docs-trigger')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.AMPERSAND_OPS_PAT }}
          ref: main

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Check for changes in the docs
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'src/**'

      - name: Notify if no changes have happened since last run
        if: steps.filter.outputs.docs == 'false' && github.event_name == 'pull_request'
        run: echo 'No changes since last run'
        shell: bash

      - name: Test for broken links in the docs
        run: cd src && pnpm i && pnpm run test:links
        shell: bash

      - name: Generate API ref pages
        run: cd src && pnpm i && pnpm run generate
        shell: bash

      - name: Push changes
        if: steps.filter.outputs.docs == 'true' || (github.event_name == 'repository_dispatch' && github.event.action == 'update-docs-trigger')
        run: |
          git config --global user.email "devops@withampersand.com"
          git config --global user.name "Ampersand Ops"
          git add src/
          git commit -m "[ampersand-ops] auto: update documentation with latest api reference"
          git remote set-url origin https://x-access-token:${{ secrets.AMPERSAND_OPS_PAT }}@github.com/${{ github.repository }}
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.AMPERSAND_OPS_PAT }}
